name: PlatformIO Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache PlatformIO and pip
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio/
          ~/.cache/pip
        key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install PlatformIO
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: PlatformIO Tests
      run: |
        pio test -e test_native --junit-output-path test-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: platformio-test-results
        path: test-results.xml
        if-no-files-found: error
    - name: Publish test results
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}
      with:
        name: PlatformIO Tests
        path: test-results.xml
        reporter: java-junit
